/**
 * The Straive frame around the demo.
 *
 * There is a deliberate line drawn here. Everything above this bar is Straive:
 * the brand, the disclosure that the data is synthetic, and the two switches
 * that control the demonstration itself. Everything below it is ProSports, the
 * fictional retailer. A viewer should never have to wonder which part of the
 * screen is the shop and which part is us looking at it.
 *
 * Moving the personalization and panel switches up here also emptied the
 * storefront header of demo scaffolding, which is what finally let it look like
 * a retail site rather than a control console.
 */

import React from 'react';
import { useApp } from '../../context/AppContext';
import { StraiveLogo } from '../brand/StraiveLogo';
import { Sparkles, PanelRightOpen, PanelRightClose, FlaskConical } from 'lucide-react';

export const AppBar: React.FC = () => {
  const { isPersonalizationOn, togglePersonalization, showMLPanel, toggleMLPanel } = useApp();

  return (
    <div className="shrink-0 bg-ink-950 text-white border-b border-white/10">
      <div className="px-4 h-12 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3 min-w-0">
          <StraiveLogo className="h-[18px]" />
          <span className="hidden md:block h-4 w-px bg-white/15" />
          <span className="hidden md:block text-[11px] font-semibold tracking-wide text-slate-300 truncate font-display">
            Commerce Personalization Intelligence
          </span>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          {/* The storefront below is convincing enough that a viewer who never
              opens a deep dive could take it for a live site. Say so, always. */}
          <span
            className="hidden lg:flex items-center gap-1.5 text-[10px] font-semibold text-straive-200 bg-straive-950/60 border border-straive-800/70 rounded-full px-2.5 py-1"
            title="Catalog, shoppers and order history are generated by a seeded simulator. No real customer data is used anywhere in this prototype."
          >
            <FlaskConical className="h-3 w-3" />
            Synthetic data · simulated models
          </span>

          <button
            onClick={togglePersonalization}
            title="Turn the three engines on or off and watch the storefront change"
            className={`flex items-center gap-1.5 pl-2 pr-2.5 py-1.5 rounded-full text-[11px] font-bold transition-all border ${
              isPersonalizationOn
                ? 'bg-straive-500 text-white border-straive-400 shadow-[0_0_0_3px_rgba(255,88,0,0.18)]'
                : 'bg-white/5 text-slate-300 border-white/15 hover:bg-white/10'
            }`}
          >
            <Sparkles className="h-3.5 w-3.5" />
            <span>Personalization</span>
            <span
              className={`ml-0.5 rounded-full px-1.5 py-px text-[9px] font-mono font-extrabold ${
                isPersonalizationOn ? 'bg-white/25 text-white' : 'bg-white/10 text-slate-400'
              }`}
            >
              {isPersonalizationOn ? 'ON' : 'OFF'}
            </span>
          </button>

          <button
            onClick={toggleMLPanel}
            title="Show or hide the behind-the-scenes panel"
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-full text-[11px] font-bold border bg-white/5 text-slate-300 border-white/15 hover:bg-white/10 hover:text-white transition-all"
          >
            {showMLPanel ? <PanelRightClose className="h-3.5 w-3.5" /> : <PanelRightOpen className="h-3.5 w-3.5" />}
            <span className="hidden sm:inline">{showMLPanel ? 'Hide' : 'Show'} panel</span>
          </button>
        </div>
      </div>
    </div>
  );
};
